{
    "name": "OKR",
    "version": "19.0.1.0.0",
    "category": "Custom",
    "author": "ADHOC SA",
    "depends": ["base", "hr"],
    "data": [
        "security/res_group.xml",
        "security/ir.model.access.csv",
        "security/ir.rule.xml",
        "data/ir_cron.xml",
        "views/okr_views.xml",
        "views/okr_key_result_views.xml",
        "views/okr_objective_views.xml",
        "views/okr_menus.xml",
    ],
    "installable": True,
    "application": True,
    "license": "AGPL-3",
}
